### ISSUE TITLE
[Epic] Bug Fixing

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#243]
**Known Bugs**

- [x] https://github.com/onflow/flow-playground/issues/630
- [x] https://github.com/onflow/flow-playground/issues/626
- [x] https://github.com/onflow/flow-playground/issues/632
- [x] https://github.com/onflow/flow-playground/issues/635
- [x] https://github.com/onflow/flow-playground-api/issues/246 (needs to be looked at)
- [x] https://github.com/onflow/flow-playground-api/issues/249
- [x] https://github.com/onflow/flow-playground-api/issues/250
- [x] https://github.com/onflow/flow-playground/issues/642
- [x] https://github.com/onflow/flow-playground-api/issues/255
